# Generated by Django 5.2.14 on 2026-05-14 15:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                ("shop_name", models.CharField(max_length=120)),
                ("shop_slug", models.SlugField(unique=True)),
                ("legal_name", models.CharField(max_length=200)),
                (
                    "business_license",
                    models.FileField(
                        blank=True, null=True, upload_to="vendor/licenses/"
                    ),
                ),
                (
                    "union_license",
                    models.FileField(
                        blank=True, null=True, upload_to="vendor/licenses/"
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=255)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.02"), max_digits=5
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("applied", "در انتظار"),
                            ("approved", "تأیید شد"),
                            ("suspended", "تعلیق"),
                            ("rejected", "رد شد"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_sales", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="vendor/logos/"),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("melted", "طلای آب\u200cشده"),
                            ("jewelry", "طلای ساخته\u200cشده"),
                            ("coin", "سکه"),
                            ("silver", "نقره"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("weight_mg", models.BigIntegerField()),
                ("karat", models.PositiveSmallIntegerField(default=750)),
                (
                    "manufacturing_fee_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "vendor_margin_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("fixed_extra_rial", models.BigIntegerField(default=0)),
                ("coin_type", models.CharField(blank=True, max_length=20)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("stock", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="marketplace.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "category", "-created_at"],
                        name="marketplace_vendor__35c3d6_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="marketplace_is_acti_39fb3f_idx",
                    ),
                ],
            },
        ),
    ]
