# Generated by Django 5.2.14 on 2026-05-14 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("gross_rial", models.BigIntegerField(default=0)),
                ("commission_rial", models.BigIntegerField(default=0)),
                ("net_rial", models.BigIntegerField(default=0)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="marketplace.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor settlement",
                "indexes": [
                    models.Index(
                        fields=["vendor", "-period_end"],
                        name="marketplace_vendor__d894c0_idx",
                    )
                ],
            },
        ),
    ]
