# Generated by Django 5.2.14 on 2026-05-14 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_vendorsettlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "post-pishtaz" / "tipax" / "snapp-box"',
                        max_length=40,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text='"online" / "snappay" / "gsmpay"',
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("locked_unit_price_rial", models.BigIntegerField()),
                ("locked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("flat", "مبلغ ثابت (ریال)")],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="0.10 for percent; 100000 for flat rial.",
                        max_digits=12,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("uses", models.PositiveIntegerField(default=0)),
                ("min_order_rial", models.BigIntegerField(default=0)),
                (
                    "max_discount_rial",
                    models.BigIntegerField(default=0, help_text="0 = no cap"),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. خانه / محل کار", max_length=80),
                ),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_phone", models.CharField(max_length=15)),
                ("recipient_national_id", models.CharField(blank=True, max_length=10)),
                ("province", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=80)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="0.10 = 10%; applied as a discount on the computed price.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_cost_rial",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_methods",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of methods, e.g. ["post-pishtaz", "tipax", "snapp-box"].',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="apps.jewelry.JewelryCategory.code, e.g. 'ring' / 'necklace'",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("melted", "طلای آب\u200cشده"),
                    ("jewelry", "طلای ساخته\u200cشده"),
                    ("coin", "سکه"),
                    ("silver", "نقره"),
                    ("ingot", "شمش طلا"),
                    ("leather_bracelet", "دستبند چرمی"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "karat", "weight_mg"],
                name="marketplace_categor_c98958_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sub_category_code", "is_active"],
                name="marketplace_sub_cat_b86cb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="marketplace_brand_7500d0_idx"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketplace.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="marketplace.product",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_carts",
                to="marketplace.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="marketplace.shippingaddress",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "-locked_at"], name="marketplace_cart_id_a1d69b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddIndex(
            model_name="shippingaddress",
            index=models.Index(
                fields=["user", "-updated_at"], name="marketplace_user_id_3b07fd_idx"
            ),
        ),
    ]
