# Generated by Django 5.2.14 on 2026-05-14 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(db_index=True, max_length=40)),
                ("rial_price", models.BigIntegerField()),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("source", models.CharField(default="tgju", max_length=20)),
            ],
            options={
                "verbose_name": "Price tick",
                "indexes": [
                    models.Index(
                        fields=["source_key", "-captured_at"],
                        name="pricing_pri_source__f398fa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PricingFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("value", models.DecimalField(decimal_places=8, max_digits=18)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceQuote",
            fields=[
                (
                    "quote_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("side", models.CharField(max_length=4)),
                ("price_per_mg_rial", models.BigIntegerField()),
                ("valid_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "base_tick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.pricetick",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price quote",
                "indexes": [
                    models.Index(
                        fields=["asset", "side", "-created_at"],
                        name="pricing_pri_asset_5a4ad4_idx",
                    ),
                    models.Index(
                        fields=["valid_until"], name="pricing_pri_valid_u_552d10_idx"
                    ),
                ],
            },
        ),
    ]
