# Generated by Django 5.2.14 on 2026-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingformula",
            name="value",
            field=models.DecimalField(decimal_places=8, max_digits=24),
        ),
    ]
