# Generated by Django 5.2.14 on 2026-05-14 15:33

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        default=apps.orders.models.generate_order_number,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("buy_gold", "خرید طلا از سامانه"),
                            ("sell_gold", "فروش طلا به سامانه"),
                            ("buy_silver", "خرید نقره از سامانه"),
                            ("sell_silver", "فروش نقره به سامانه"),
                            ("marketplace", "خرید از فروشنده"),
                            ("wallet_topup", "شارژ کیف پول"),
                            ("dca", "خرید دوره\u200cای"),
                            ("subscription", "اشتراک ویژه"),
                            ("auction_bid", "پیشنهاد در حراج"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("awaiting_payment", "در انتظار پرداخت"),
                            ("paid", "پرداخت شد"),
                            ("processing", "در حال پردازش"),
                            ("completed", "تکمیل شد"),
                            ("expired", "منقضی شد"),
                            ("cancelled", "لغو شد"),
                            ("refunded", "بازگشت داده شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("price_per_mg_rial", models.BigIntegerField(default=0)),
                ("mg_amount", models.BigIntegerField(default=0)),
                ("rial_amount", models.BigIntegerField(default=0)),
                ("commission_rial", models.BigIntegerField(default=0)),
                ("commission_mg", models.BigIntegerField(default=0)),
                ("payment_deadline", models.DateTimeField(blank=True, null=True)),
                ("payment_gateway", models.CharField(blank=True, max_length=20)),
                ("payment_ref", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_pdf",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing.pricequote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="marketplace.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_snapshot", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_rial", models.BigIntegerField()),
                ("line_total_rial", models.BigIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["state", "payment_deadline"],
                name="orders_orde_state_c88f6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor", "-created_at"], name="orders_orde_vendor__b1769d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant_id", "kind", "-created_at"],
                name="orders_orde_tenant__0a9efb_idx",
            ),
        ),
    ]
