# Generated by Django 5.2.14 on 2026-05-14 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=80)),
                ("category", models.CharField(db_index=True, max_length=20)),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("severity", models.CharField(default="info", max_length=10)),
                ("outcome", models.CharField(default="success", max_length=10)),
                ("state_from", models.CharField(blank=True, max_length=40)),
                ("state_to", models.CharField(blank=True, max_length=40)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit entry",
                "verbose_name_plural": "Audit entries",
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="audit_audit_kind_60dc51_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "-created_at"],
                        name="audit_audit_actor_i_14855e_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__e2abcf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(db_index=True, max_length=40)),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Idempotency key",
                "unique_together": {("scope", "key")},
            },
        ),
    ]
