# Generated by Django 5.2.14 on 2026-05-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JewelryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("title_fa", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("sort", models.PositiveSmallIntegerField(default=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="jewelry.jewelrycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "title_fa"],
            },
        ),
    ]
