# Generated by Django 5.2.14 on 2026-05-14 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(default="gold", max_length=10)),
                ("requested_mg", models.BigIntegerField()),
                ("bars_breakdown", models.JSONField(blank=True, default=dict)),
                ("processing_fee_rial", models.BigIntegerField(default=0)),
                ("tracking_code", models.CharField(blank=True, max_length=40)),
                ("shipping_address", models.TextField()),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_national_id", models.CharField(max_length=10)),
                ("recipient_phone", models.CharField(max_length=15)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("approved", "تأیید شد"),
                            ("minting", "در حال ضرب و پلمپ"),
                            ("shipped", "ارسال شد"),
                            ("delivered", "تحویل داده شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
