# Generated by Django 5.2.14 on 2026-05-14 15:33

import apps.accounts.models
import apps.security.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                ("phone", models.CharField(db_index=True, max_length=11, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                (
                    "national_id",
                    apps.security.fields.EncryptedCharField(blank=True, max_length=255),
                ),
                (
                    "national_id_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("father_name", models.CharField(blank=True, max_length=80)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "iban",
                    apps.security.fields.EncryptedCharField(blank=True, max_length=255),
                ),
                (
                    "iban_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_vendor", models.BooleanField(default=False)),
                ("is_frozen", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("plus", "Plus"),
                            ("pro", "Pro"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("share_trades", models.BooleanField(default=False)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_secret",
                    apps.security.fields.EncryptedCharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("empty", "هیچ مدرکی ارسال نشده"),
                            ("submitted", "ارسال شد"),
                            ("under_review", "در حال بررسی"),
                            ("approved", "تأیید شد"),
                            ("rejected", "رد شد"),
                            ("requires_more", "نیاز به اطلاعات بیشتر"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                (
                    "national_card_front",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                (
                    "national_card_back",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                (
                    "selfie_with_card",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                (
                    "birth_certificate",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                (
                    "video_attestation",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                ("card_pan_masked", models.CharField(blank=True, max_length=20)),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Submission",
                "verbose_name_plural": "KYC Submissions",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=11)),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "ورود/ثبت\u200cنام"),
                            ("withdraw", "تأیید برداشت"),
                            ("transfer", "تأیید انتقال"),
                            ("change_iban", "تغییر شبا"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "expires_at"],
                        name="accounts_ot_phone_edc003_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant_id", "phone"], name="accounts_us_tenant__1bea01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified", "is_phone_verified"],
                name="accounts_us_is_veri_78725c_idx",
            ),
        ),
    ]
