# Generated by Django 5.2.14 on 2026-05-14 15:33

import apps.wallet.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                (
                    "address",
                    models.CharField(
                        default=apps.wallet.models.generate_gold_address,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "balance_mg",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "locked_mg",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "silver_balance_mg",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "silver_locked_mg",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance_mg__gte", 0)),
                        name="goldwallet_gold_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("silver_balance_mg__gte", 0)),
                        name="goldwallet_silver_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locked_mg__lte", models.F("balance_mg"))),
                        name="goldwallet_gold_locked_le_balance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("silver_locked_mg__lte", models.F("silver_balance_mg"))
                        ),
                        name="goldwallet_silver_locked_le_balance",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RialWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="default", max_length=40),
                ),
                ("currency", models.CharField(default="IRR", max_length=8)),
                (
                    "balance_rial",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "locked_rial",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rial_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rial wallet",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance_rial__gte", 0)),
                        name="rialwallet_balance_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locked_rial__gte", 0)),
                        name="rialwallet_locked_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("locked_rial__lte", models.F("balance_rial"))
                        ),
                        name="rialwallet_locked_le_balance",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "واریز ریالی"),
                            ("withdraw", "برداشت ریالی"),
                            ("buy_gold", "خرید طلا"),
                            ("sell_gold", "فروش طلا"),
                            ("buy_silver", "خرید نقره"),
                            ("sell_silver", "فروش نقره"),
                            ("transfer_in", "انتقال ورودی"),
                            ("transfer_out", "انتقال خروجی"),
                            ("yield_payout", "سود روزانه"),
                            ("delivery_burn", "تحویل فیزیکی"),
                            ("commission", "کارمزد"),
                            ("adjustment", "اصلاح ادمین"),
                            ("refund", "بازگشت وجه"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        choices=[
                            ("rial", "rial"),
                            ("gold", "gold"),
                            ("silver", "silver"),
                        ],
                        max_length=8,
                    ),
                ),
                ("rial_amount", models.BigIntegerField(default=0)),
                ("mg_amount", models.BigIntegerField(default=0)),
                ("balance_after_rial", models.BigIntegerField(blank=True, null=True)),
                ("balance_after_mg", models.BigIntegerField(blank=True, null=True)),
                (
                    "event_id",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_txs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet transaction",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="wallet_wall_user_id_801842_idx",
                    ),
                    models.Index(
                        fields=["related_order"], name="wallet_wall_related_607675_idx"
                    ),
                    models.Index(
                        fields=["type", "-created_at"],
                        name="wallet_wall_type_18698d_idx",
                    ),
                ],
            },
        ),
    ]
