# Generated by Django 5.2.14 on 2026-05-14 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("zarinpal", "زرین\u200cپال"),
                            ("idpay", "آیدی\u200cپی"),
                            ("payping", "پی\u200cپینگ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_rial", models.BigIntegerField()),
                (
                    "authority",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("ref_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("card_pan_masked", models.CharField(blank=True, max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("redirected", "در درگاه"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                            ("expired", "منقضی"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment attempt",
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="payments_pa_order_i_37df30_idx",
                    ),
                    models.Index(
                        fields=["gateway", "state"],
                        name="payments_pa_gateway_e900b1_idx",
                    ),
                ],
            },
        ),
    ]
