# Generated by Django 5.2.14 on 2026-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("title_fa", models.CharField(max_length=80)),
                ("weight_mg", models.BigIntegerField()),
                (
                    "gold_content_mg",
                    models.BigIntegerField(
                        help_text="میلی\u200cگرم طلای خالص داخل سکه"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="coins/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
